### ISSUE TITLE
Error: You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by FilipeCovas** [axeldelafosse/expo-next-monorepo-example#13]
hi, i followed the guide to start the package and gave this error when running yarn dev:expo, does anyone know how I can solve it?

![Screenshot Capture - 2021-11-07 - 19-53-09](https://user-images.githubusercontent.com/16358314/140659743-394b2fe6-2b8e-45f7-96ab-ad910a5bc604.png)

**Comment by nandorojo** [comment]
This is usually a next transpile modules issue. Did you clone the repo or make it yourself

**Comment by FilipeCovas** [comment]
> This is usually a next transpile modules issue. Did you clone the repo or make it yourself

Hi Fernando, thanks for the reply, I cloned the repo

**Comment by Raseed-Team** [comment]
If it's any help - to get [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) working on next I modified the `next.config.js`. 

I first installed `next-fonts` as a dev dependancy on expo. Then I included it in the `next.config.js` by doing the following

```
const { withExpo } = require('@expo/next-adapter')
const withPlugins = require('next-compose-plugins')
const withBundleAnalyzer = require('@next/bundle-analyzer')({
    enabled: process.env.ANALYZE === 'true'
})
const withTM = require('next-transpile-modules')([
    'app',
    '@gorhom/bottom-sheet',
    '@gorhom/portal',
    'dripsy',
    '@dripsy/core'
])
const withFonts = require('next-fonts')
const nextConfig = {}

module.exports = withPlugins(
    [
        withFonts(),
        withTM,
        withBundleAnalyzer,
        [withExpo, { projectRoot: __dirname + '/../..' }]
    ],
    nextConfig
)
```

I noticed if I changed the order of the array parameter used in `withPlugins` the next app would crash.

Does anyone know why the order of items in the `withPlugins` array matters?

**Comment by nandorojo** [comment]
You should pass with fonts directly, not call the function.

**Comment by nandorojo** [comment]
> Does anyone know why the order of items in the withPlugins array matters?

it’s the order in which the next config gets updated, so presumably that matters or someone is incorrectly forwarding. I think expo just has to be last.

**Comment by Raseed-Team** [comment]
@nandorojo Thank you - that was helpful :)

**Comment by nandorojo** [comment]
> hi, i followed the guide to start the package and gave this error when running yarn dev:expo, does anyone know how I can solve it?
> 
> ![Screenshot Capture - 2021-11-07 - 19-53-09](https://user-images.githubusercontent.com/16358314/140659743-394b2fe6-2b8e-45f7-96ab-ad910a5bc604.png)

@FilipeCovas I just realized this issue. You said you ran `yarn dev:expo`? Did you then open that in the browser? `yarn dev:expo` should only be used for iOS and Android. For Web, you should use `yarn dev:next`. Remember, this is for Next.js to run in the browser.

**Comment by FilipeCovas** [comment]
> > hi, i followed the guide to start the package and gave this error when running yarn dev:expo, does anyone know how I can solve it?
> 
> > 
> 
> > ![Screenshot Capture - 2021-11-07 - 19-53-09](https://user-images.githubusercontent.com/16358314/140659743-394b2fe6-2b8e-45f7-96ab-ad910a5bc604.png)
> 
> 
> 
> @FilipeCovas I just realized this issue. You said you ran `yarn dev:expo`? Did you then open that in the browser? `yarn dev:expo` should only be used for iOS and Android. For Web, you should use `yarn dev:next`. Remember, this is for Next.js to run in the browser.

Hi @nandorojo, thank you very much for the clarification 🙏🏼🙌🏼

**Comment by nandorojo** [comment]
@axeldelafosse maybe we should add that to the readme to make it clearer how to run each platform. The `yarn dev:` commands are useful to mention either way.
