### ISSUE TITLE
TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by oste** [axeldelafosse/expo-next-monorepo-example#14]
I am finding that deleting the yarn.lock file and attempting to reinstall can produce this error.

I am using yarn 1.22.15

<img width="964" alt="Screen Shot 2021-11-09 at 9 45 12 PM" src="https://user-images.githubusercontent.com/350275/141040204-d14479c2-d7a8-4212-865c-ec055cd4aa49.png">
.

**Comment by nandorojo** [comment]
You shouldn’t be deleting your lock file, why are you doing that? Can you use the monorepo linked to here under resources to reproduce? https://fernandorojo.co/conf

**Comment by oste** [comment]
Yeah it’s probably not ideal to delete the lock file. Sometimes I do this to rule out other issues since it should provide e fresh install.

**Comment by nandorojo** [comment]
Yeah you shouldn’t remove it, that can mess up all the dependencies.

**Comment by marklawlor** [comment]
@oste @nandorojo This issue is caused in NextJS `12.0.3`. Locking to `12.0.2` or `12.0.4-canary.4` will fix the issue

Issue causes by internal NextJS paths conflicting with the babel `.web.ts` path loading https://github.com/vercel/next.js/pull/31116
