### ISSUE TITLE
Icons & Images don't work...

### ISSUE THREAD

**Issue by Rychillie** [axeldelafosse/expo-next-monorepo-example#22]
I spent the weekend testing the repository creating a responsive navigation, but I ran into a problem with Icons and Images.

Trying with Expo Vector Icons and React Native's Image Component. In the Expo mobile application, the icon appears perfectly, however in NextJS when my navigation is rendered, the icon or image does not appear.

I would like to understand what happens and if possible a tip on how I can create an image component to be used in both NextJS and Expo, both for icons in menus and for the rest of the application.

This application I'm making is a study only, I was interested in the repository and would like to see how it can be applied to my workflow.

NextJS Screenshot React Navigation: 
![NextJS Screenshot](https://user-images.githubusercontent.com/14102456/144873350-419ffe18-a21d-43ce-95d2-fddf6963ceac.png)

Expo Screenshot React Navigation:
![Expo Screenshot](https://user-images.githubusercontent.com/14102456/144873109-7bd81195-9bc2-4cc7-8619-2c994062b24e.png)

**Comment by nandorojo** [comment]
You need to install next-images and next-font

**Comment by nandorojo** [comment]
See https://docs.expo.dev/guides/using-nextjs
