### ISSUE TITLE
Remix.run integration as alternative to Next?

### ISSUE THREAD

**Issue by algoflows** [axeldelafosse/expo-next-monorepo-example#24]
Hi All,

Amazing work so far, massive fan of this repo!

Remix being the new SSR framework from the guys who made React Router (Its pretty amazing).

www.remix.run <----------- pure awesomness

Just throwing this out there to hear your thoughts, do you think a Nextjs could be easily swapped out in favour of using Remix in this monorepo, would we be able to use shared screens?

Thanks for any help on this :)

😄

**Comment by axeldelafosse** [comment]
Hey Sean! Thanks! Sorry but this is out of scope, the goal of this example is to show how to use Next.js and Expo together. We are not planning to use Remix.

**Comment by nandorojo** [comment]
I opened a discussion on the Remix repo; I think that's a better place for this. Feel free to chime in: https://github.com/remix-run/remix/discussions/1578
