### ISSUE TITLE
Problems runnning expo

### ISSUE THREAD

**Issue by danielkv** [axeldelafosse/expo-next-monorepo-example#29]
So far I managed to run on NextJS, it's running smooth. I having problems running the expo part. (I'm not using `expo-dev-client` for now, just want to make it work first)

1. The `console.log` is not working, does not give me any messages
2. The fast refresh is not working, already checked the metro config, it seems to be right

**Comment by danielkv** [comment]
I ended up using a different config on `metro.config.js` with the lib `expo-yarn-workspaces`:

```js
const { createMetroConfiguration } = require('expo-yarn-workspaces');

const config = createMetroConfiguration(__dirname);

delete config.resolver.extraNodeModules['@labook/web'];

module.exports = config;
```

It worked like a charm, no further configuration

**Comment by axeldelafosse** [comment]
This repo is now deprecated in favour of [Solito](https://solito.dev)
