### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by abeaclark** [axeldelafosse/expo-next-monorepo-example#4]
Thanks for a great resource here! Curious if you're open to adding a license so I can understand the copyright restrictions of using parts of this code / approach.

Thanks!

**Comment by axeldelafosse** [comment]
Hey-- oh sorry I thought it was added already.

Just added a MIT license: https://github.com/axeldelafosse/expo-next-monorepo-example/blob/main/LICENSE.md

Thank you!
