### ISSUE TITLE
Is server side rendering possible?

### ISSUE THREAD

**Issue by fikrikarim** [axeldelafosse/expo-next-monorepo-example#6]
Hi. Thanks for creating this monorepo. 

I wonder whether server side rendering is possible here? I tried the example but couldn't get the SSR working.

**Comment by jcarraway** [comment]
@nandorojo sorry to dig up this old issue, but could you help me understand the appeal of Next.js without SSR / SSG? I know there are more features to Next than just ssr/ssg but seems like it adds a lot of overhead esp with navigation while missing out on one of the key features. Any thoughts appreciated!

**Comment by nandorojo** [comment]
I'd rank code splitting alone pretty high. Also you can still get the SSG benefits of data fetching for SEO meta tags/initial client-side render.

**Comment by jcarraway** [comment]
Okay thanks. I just wanted to make sure I wasn't missing anything. I have this repo cloned and running with Moti, Stripe, Apollo, and a few other toys and having fun so far. The navigation bit is a little tedious, but it's a small price to pay for such powerful tool.

**Comment by nandorojo** [comment]
Yeah the navigation is pretty repetitive as it is. I anticipate this not being the case once Expo gets rid of Metro. Once that’s the case, we’ll be able to use the pages folder for navigation on Native, too.

I’m also working on a library that abstracts a good amount of the navigation code from this repo.

**Comment by jcarraway** [comment]
I'll be on the lookout - really appreciate all your work in this space
